# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conu/ui/ui_files/SelectWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectWindow(object):
    def setupUi(self, SelectWindow):
        SelectWindow.setObjectName("SelectWindow")
        SelectWindow.resize(944, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("conu/ui/ui_files\\../../assets/conu_logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SelectWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SelectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    background-color: #05668d;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    margin: 0px 0px 20px 0px;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 2)
        self.selectwindow_txtSearch = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.selectwindow_txtSearch.setFont(font)
        self.selectwindow_txtSearch.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-width: 2px;\n"
"    border-color: #028090;\n"
"}")
        self.selectwindow_txtSearch.setClearButtonEnabled(True)
        self.selectwindow_txtSearch.setObjectName("selectwindow_txtSearch")
        self.gridLayout.addWidget(self.selectwindow_txtSearch, 2, 0, 1, 2)
        self.selectwindow_tblSelect = QtWidgets.QTableWidget(self.centralwidget)
        self.selectwindow_tblSelect.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.selectwindow_tblSelect.setStyleSheet("QTableWidget {\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    border-color: black;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QTableWidget:focus {\n"
"    border-width: 2px;\n"
"    border-color: #028090;\n"
"}")
        self.selectwindow_tblSelect.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.selectwindow_tblSelect.setTabKeyNavigation(False)
        self.selectwindow_tblSelect.setAlternatingRowColors(False)
        self.selectwindow_tblSelect.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.selectwindow_tblSelect.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.selectwindow_tblSelect.setCornerButtonEnabled(False)
        self.selectwindow_tblSelect.setObjectName("selectwindow_tblSelect")
        self.selectwindow_tblSelect.setColumnCount(0)
        self.selectwindow_tblSelect.setRowCount(0)
        self.selectwindow_tblSelect.horizontalHeader().setStretchLastSection(True)
        self.selectwindow_tblSelect.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.selectwindow_tblSelect, 3, 0, 1, 2)
        self.selectwindow_btnSelect = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectwindow_btnSelect.sizePolicy().hasHeightForWidth())
        self.selectwindow_btnSelect.setSizePolicy(sizePolicy)
        self.selectwindow_btnSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.selectwindow_btnSelect.setStyleSheet("QPushButton {\n"
"    width: 60px;\n"
"    color: white;\n"
"    background-color: #006494;\n"
"    border-style: outset;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        background-color: #0582ca;\n"
"}")
        self.selectwindow_btnSelect.setObjectName("selectwindow_btnSelect")
        self.gridLayout.addWidget(self.selectwindow_btnSelect, 4, 1, 1, 1)
        SelectWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SelectWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 944, 21))
        self.menubar.setObjectName("menubar")
        SelectWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SelectWindow)
        self.statusbar.setObjectName("statusbar")
        SelectWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SelectWindow)
        QtCore.QMetaObject.connectSlotsByName(SelectWindow)

    def retranslateUi(self, SelectWindow):
        _translate = QtCore.QCoreApplication.translate
        SelectWindow.setWindowTitle(_translate("SelectWindow", "Select"))
        self.label_4.setText(_translate("SelectWindow", "SELECT"))
        self.selectwindow_txtSearch.setPlaceholderText(_translate("SelectWindow", "Search"))
        self.selectwindow_tblSelect.setSortingEnabled(True)
        self.selectwindow_btnSelect.setText(_translate("SelectWindow", "Select"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelectWindow = QtWidgets.QMainWindow()
    ui = Ui_SelectWindow()
    ui.setupUi(SelectWindow)
    SelectWindow.show()
    sys.exit(app.exec_())
