global_assignees = dict()
global_assigneedepartments = dict()
global_departments = dict()
global_userdepartments = dict()
global_forms = dict()
global_prioritylevels = dict()
global_sites = dict()
global_users = dict()
