from enum import Enum


class Page(Enum):

    ASSIGNEE_LISTINGVIEW = 0
    ASSIGNEE_ENTRYFORM = 1

    DEPARTMENT_LISTINGVIEW = 2
    DEPARTMENT_ENTRYFORM = 3

    FORM_LISTINGVIEW = 4
    FORM_ENTRYFORM = 5
